# http://about.travis-ci.org/docs/user/build-configuration/
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-19mode
gemfile: Gemfile.ci
env:
   - JRUBY_OPTS="--1.9"
matrix:
  allow_failures:
    - rvm: 1.8.7
